## Läs in data

In [ ]:
import pandas as pd


df = pd.read_csv("data/historical_data.csv")


print(f"Antal rader och kolumner: {df.shape} \n") #datasetstorlek
print(f"{df.info()} \n") #datatyper
print(f"Antal misstänkta(1)/icke misstänkta(0):\n{df["is_suspicious"].value_counts()}") #targetfördelning

Antal rader och kolumner: (12000, 18)

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          12000 non-null  int64
 1   day                         12000 non-null  int64
 2   event_type                  12000 non-null  str
 3   category                    12000 non-null  str
 4   region                      11660 non-null  str
 5   device                      12000 non-null  str
 6   account_age_days            12000 non-null  float64
 7   num_prev_listings           12000 non-null  int64
 8   prev_reports_30d            12000 non-null  int64
 9   verification_level          12000 non-null  int64
 10  price                       11182 non-null  float64
 11  num_images                  12000 non-null  int64
 12  message_length              12000 non-null  int64
 13  contains_off_platform       12000 non-null  int64
 14  urgency_words               12000 non-null  int64
 15  payment_attempt             12000 non-null  int64
 16  time_to_first_response_min  11410 non-null  float64
 17  is_suspicious               12000 non-null  int64
dtypes: float64(3), int64(11), str(4)
memory usage: 1.6 MB
None

Antal misstänkta(1)/icke misstänkta(0):
is_suspicious
0    10776
1     1224
Name: count, dtype: int64

In [30]:
print(f"Antal saknade värden: \n{df.isna().sum()}") #enklare överblick över saknade värden

display(df.head())
display(df.describe().T)

Antal saknade värden:
id                              0
day                             0
event_type                      0
category                        0
region                        340
device                          0
account_age_days                0
num_prev_listings               0
prev_reports_30d                0
verification_level              0
price                         818
num_images                      0
message_length                  0
contains_off_platform           0
urgency_words                   0
payment_attempt                 0
time_to_first_response_min    590
is_suspicious                   0
dtype: int64

,id,day,event_type,category,region,device,account_age_days,num_prev_listings,prev_reports_30d,verification_level,price,num_images,message_length,contains_off_platform,urgency_words,payment_attempt,time_to_first_response_min,is_suspicious
0,0,8,ad_post,other,urban,android,38.4,2,1,1,594.16,3,91,0,1,0,2.3,0
1,1,4,ad_post,fashion,urban,android,20.0,1,0,1,134.47,2,150,0,0,0,13.6,0
2,2,4,ad_post,other,metro,ios,46.7,3,1,1,198.52,3,72,0,0,0,4.2,0
3,3,3,ad_post,furniture,metro,android,44.3,3,1,2,141.20,3,0,0,0,0,19.8,0
4,4,1,ad_post,electronics,metro,web,211.2,5,0,0,81.39,3,9,0,0,1,23.3,0

,count,mean,std,min,25%,50%,75%,max
id,12000.0,5999.500000,3464.245950,0.00,2999.750,5999.500,8999.250,11999.00
day,12000.0,7.482667,4.032520,1.00,4.000,7.000,11.000,14.00
account_age_days,12000.0,99.632567,112.903541,2.20,36.300,66.600,120.700,2741.70
num_prev_listings,12000.0,3.027750,1.766467,0.00,2.000,3.000,4.000,12.00
prev_reports_30d,12000.0,0.151500,0.386083,0.00,0.000,0.000,0.000,3.00
verification_level,12000.0,0.710167,0.719171,0.00,0.000,1.000,1.000,2.00
price,11182.0,207.348603,196.226023,7.67,86.195,149.225,256.795,2743.08
num_images,12000.0,2.870417,1.766886,0.00,2.000,3.000,4.000,10.00
message_length,12000.0,111.154417,66.396885,0.00,63.000,108.000,155.000,416.00
contains_off_platform,12000.0,0.072833,0.259874,0.00,0.000,0.000,0.000,1.00
urgency_words,12000.0,0.099083,0.298786,0.00,0.000,0.000,0.000,1.00
payment_attempt,12000.0,0.181167,0.385172,0.00,0.000,0.000,0.000,1.00
time_to_first_response_min,11410.0,22.160438,28.834047,0.30,6.700,13.400,26.600,579.80
is_suspicious,12000.0,0.102000,0.302661,0.00,0.000,0.000,0.000,1.00